# Generated by Django 3.0.5 on 2020-04-25 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0009_auto_20200425_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_notes',
            name='book_isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book_info'),
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 7, 24, 530392)),
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 17, 7, 24, 530392)),
        ),
        migrations.AlterField(
            model_name='borrower_computer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 7, 24, 532392)),
        ),
        migrations.AlterField(
            model_name='borrower_computer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 22, 24, 532392)),
        ),
        migrations.AlterField(
            model_name='borrower_tutor_room',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 7, 24, 531392)),
        ),
        migrations.AlterField(
            model_name='borrower_tutor_room',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 22, 24, 531392)),
        ),
    ]
