# Generated by Django 3.0.5 on 2020-04-26 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0019_auto_20200426_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_type',
            options={'ordering': ('all_type_name',), 'verbose_name': 'เพิ่มประเภทของหนังสือ', 'verbose_name_plural': 'ประเภทของหนังสือ'},
        ),
        migrations.AlterModelOptions(
            name='book_info',
            options={'ordering': ('name_book',), 'verbose_name': 'เพิ่มหนังสือ', 'verbose_name_plural': 'หนังสือทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='book_type',
            options={'ordering': ('type_book',), 'verbose_name': 'เพิ่มประเภทย่อยของหนังสือ', 'verbose_name_plural': 'ประเภทย่อยของหนังสือ'},
        ),
        migrations.AlterModelOptions(
            name='borrow_notes',
            options={'verbose_name': 'เพิ่มบันทึกการยืมหนังสือ', 'verbose_name_plural': 'บันทึกการยืมหนังสือ'},
        ),
        migrations.AlterModelOptions(
            name='borrower_computer',
            options={'verbose_name': 'เพิ่มผู้ยืมคอมพิวเตอร์', 'verbose_name_plural': 'ผู้ที่ยืมคอมพิเตอร์'},
        ),
        migrations.AlterModelOptions(
            name='borrower_tutor_room',
            options={'verbose_name': 'เพิ่มผู้ยืมห้องติวหนังสือ', 'verbose_name_plural': 'ผู้ที่ยืมห้องติวหนังสือ'},
        ),
        migrations.AlterModelOptions(
            name='calculatefines',
            options={'verbose_name': 'เพิ่มบันทึกค่าปรับ', 'verbose_name_plural': 'บันทึกค่าปรับ'},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ('name_com',), 'verbose_name': 'เพิ่มคอมพิวเตอร์', 'verbose_name_plural': 'คอมพิวเตอร์'},
        ),
        migrations.AlterModelOptions(
            name='idcard',
            options={'verbose_name': 'เพิ่มรหัสบัตรประชาชนของ user', 'verbose_name_plural': 'รหัสบัตรประชาชนของ user'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',), 'verbose_name': 'เพิ่มสำนักพิมพ์', 'verbose_name_plural': 'สำนักพิมพ์'},
        ),
        migrations.AlterModelOptions(
            name='tutor_room',
            options={'ordering': ('name_room',), 'verbose_name': 'เพิ่มห้องติว', 'verbose_name_plural': 'ห้องติว'},
        ),
        migrations.AlterField(
            model_name='book_type',
            name='all_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_type', to='mylibrary.All_type'),
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 50, 58, 2923)),
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 21, 50, 58, 2923)),
        ),
        migrations.AlterField(
            model_name='borrower_computer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 50, 58, 7924)),
        ),
        migrations.AlterField(
            model_name='borrower_computer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 22, 5, 58, 7924)),
        ),
        migrations.AlterField(
            model_name='borrower_tutor_room',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 50, 58, 5923)),
        ),
        migrations.AlterField(
            model_name='borrower_tutor_room',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 22, 5, 58, 5923)),
        ),
    ]
